### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by irstevenson**
I think as part of getting things setup, it'd be worth merging current `develop` into `master` so as to add CONTRIBUTING.md. That way, GitHub will be able to guide contributors to it straight away - otherwise we'll be waiting until our next relelase.

Then after this, the only merges to `master` should be for releases. ;)

Issues: #26

### CODE REVIEW

**Comment by valentingoebel** [comment]
The contributing.md looks good but it's missing a direct reference to the git flow extension https://github.com/nvie/gitflow. Casual contributors might not know that it has to be installed seperately.

I'm wondering about the commented out `bintray` section in the gradle.build. Is it still necessary or can it be removed?

**Comment by irstevenson** [comment]
I'm also wondering about that bintray bit. @jeffwils commented it out when he changed things for 3.3.0, so I'm not sure.

I guess I could just remove, because at least then we've still now got it in history. What do you think @valentingoebel ?

**Comment by irstevenson** [comment]
Like the idea of more info on git-flow tooling, so have a look see if my latest commit covers that a bit better.

Also been pondering whether to add some advice on working on the plugin, so I've added a 'Working on the code section'. Let me know if that's a good starting point - we can build on that more later I figure.

**Comment by valentingoebel** [comment]
You should definitively remove the bintray section. Everything else is perfect and can be merged.

**Comment by irstevenson** [comment]
Too easy. Consider it done. Merging now, and then we can leave master alone until next release - which hopefully will be not too far off. 👍

**Pull request merged**
